### ISSUE TITLE
google translate报错

### ISSUE THREAD

**Issue by lany9527** [ant-tool/atool-l10n#11]
### 我使用i18n-pick,扫描出文案后,使用atool-l10n自动翻译报错.
报错如下:
google translate starts: 
(node:18153) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Invalid array length
(node:18153) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.91s.

### l10n.config

![deepinscreenshot_select-area_20171106145444](https://user-images.githubusercontent.com/19483798/32428761-73645ce0-c302-11e7-88b8-7570092001ba.png)

### i18n-pick,扫描出文案:

![deepinscreenshot_select-area_20171106145606](https://user-images.githubusercontent.com/19483798/32428855-ebf52978-c302-11e7-8319-c342c16e1fc1.png)

### 请问google翻译是不是需要的数据格式不对或者是l10n.config配置存在问题?

**Comment by jaredleechn** [comment]
确实是配置有点问题，不过 google 的代码里也有些问题，你先把 from 改成 `zh-cn`

**Comment by jaredleechn** [comment]
+ atool-l10n@0.4.0 fix google translate
