### ISSUE TITLE
youdao middleware 失效

### ISSUE THREAD

**Issue by EscapeB** [ant-tool/atool-l10n#16]
好像是因为youdao api升级了= =，
另：metaToResult 中的to 可以指定多个嘛？比如一次性生车多种语言的json资源

**Comment by jaredleechn** [comment]
youdao 的我看下，metaToResult 一般是用来将本地默认填写的 defaultMessage 映射为一种基础语言，比如中文

如果想要多种语言，可以重复配置 google, youdao 这种 middleware，然后每个里面用不同的 to
