### ISSUE TITLE
How do i use this tool ?

### ISSUE THREAD

**Issue by tabaktoni** [ant-tool/atool-l10n#17]
This is my output from console.

$ node_modules/.bin/atool-l10n
     atool-l10n: summary, fetchLocal, metaToResult, youdao, reduce, save
        summary: i18n-messages/**/*.json
        summary: no local files find, run webpack with babel-plugin-react-intl first
     fetchLocal: from locales, language: en, skip true
   metaToResult: no element need to be processed
         youdao: no element need to be processed
         reduce: no element need to be processed
      save task: dest is locales

**Comment by jaredleechn** [comment]
> summary: no local files find, run webpack with babel-plugin-react-intl first

That's the problem, atool-l10n must be used together with webpack and babel-plugin-react-intl, which extract intl message out into folder `i18n-messages`

You can open two terminals, one runs webpack-dev-server or webpack build watch all the time, the other runs atool-l10n manually
